# @license
# Copyright 2022-2026 Matter.js Authors
# SPDX-License-Identifier: Apache-2.0

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        CLAUDE_CODE_VERSION: latest
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    volumes:
      - ..:/matter.js:cached
    networks:
      - "matter"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: "sleep infinity"

volumes:
  node-modules:

networks:
  matter:
    enable_ipv6: true
