name: Auto approve release PRs

on:
  pull_request:
    types: [labeled]

# Cancel previous action runs
concurrency:
  group: ${{ github.ref }}-auto-approval
  cancel-in-progress: true

jobs:
  auto-approve:
    if: |
      github.actor == 'Automator77' &&
      (github.event.label.name == 'automated-npm-release' || github.event.label.name == 'automated-chip-image-release')

    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.APPROVE_TOKEN }}
